### ISSUE TITLE
Hi ....i unable to get login credentials while entering my india mobile Number .valid mobile number is 12 digit.but ours is 10 digit.even i tried with country code .i doesnot get. .. 

### ISSUE THREAD

**Issue by KuttyArun** [DonnC/bulksmszw#2]

**Comment by DonnC** [comment]
Hie. Thanks for trying out but the service provider for the bulk sms only works in Zimbabwe, Africa only at the meantime.
It does not yet support international and hence India too, you might try an international provider with api
